---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cam1-rtsp
  namespace: default
spec:
  encryptedData:
    RTSP_URL: AgAk3xirDzWBOxZI5Rn/H2izgFsYZk77COGNm2G6i2wOxkA0jTI57jiZDZZ/frdJsr5tNWlouGpxlT/fsIv20uYZQ+6sq9ePrqBzYPI9JqpliFc8a3d4Ss0biv0HjLcpy3cFsUgB2xEpjIbFtbsrMiyWaDwHpIgbOTYS3u1U5/JVaVU88KEk3pInJziib2/Vq1rz6DpmGKuHNJKy9nIw+dW53m95iQ429bYzHEJRQ8gdDtohe6lG1RTJSX+hLBCOtZenNMKUo/y+9UrVATI/ZnaYNawL6igTRHJq82Ny1aDrtbDh1NUGaZw6gebVKNsxubsSong0qtWb6bXEydpdkpM5VCa/eaIo7/n9Gknc6w0PZ89t128OdrOCDQDIVg4TBSCCcOHT5PY+20SWz1yCqAQPXZY1ZiSFLeGA16oWUekTTBlWMSN+icr74rRuBY8QAaz+jy73lG9v7TjM1BSp1payOMVEGiSUCwg6PE4DxBZsjnJF1V/MgGsGUozjPapTIKPfhy99jYWzPzdFQGe0Kuko4Tb3uaHP8CJu3SyehFFmI4KTuDaBpYz4kapHMQJJpmI+ktXx/tpqBLOqbwQZAoSQ4G0lc0frP95uFQm+uGOE/hlR7E3vpsLb3wZ6k7rXAQnozOS0shyGm7ZqjtI56Rzqw/cTTJwuv4OV2nzMkCPO1udjGfrhawa/rk9lNkq16qO8YDQNkexby6xzkWZz7h7QG5U+D/wmoaGcWA==
  template:
    metadata:
      name: cam1-rtsp
      namespace: default
