---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cam1-rtsp
  namespace: edge-newpark
spec:
  encryptedData:
    RTSP_URL: AgBQNb64Xm8rB6Bz52u0trAxbKS4Mj+OsiErcpOSDZC4Q+RP7qPIS0A4ccgKLVPxITuKvn4lUXoMRS+mhTXrF9dnyWSQBoNvMj4j1huWsofxeV/wMoDkU79fBbAw2wsXvEkOh520R5Bl3weK1jdU2hNU263JJHlGTkJrpPXlhgHRqCdBH1GRuieUKglMnFdWR4H8bsxB6bAmIcCasb7dkY2Gsrvs53ZoRF4ajXydaNFNoWKGHMrK3rRu0AVPAYv4X3530/oSP+sJWFBsQpoHdwHh1M3/MJCY97jzGi9LW4o4u/o3pn+1EqR6EdgYf/NJ1jBY91yL2fRsp62RacYR5hPFXhDcUTVw1H81o2Q8+GokZJ8YRcSoQa8UKkNDyeQYgChEA1ASmwbum+miZuN2qEtDjQdfpADKi3/vmDISlknz6SrnqusvLFqpzCNCh4W2Nqf31rr6l0AgIDnBXioZWS2yauNs4rgIyDHsGt+GojRmOKMk8VV9qUQlu/BOriah8QLZfo1Oi0MjyYranXjuBdbO2mkTD3XnNOhH4AxSZfffP5O5w9zoju9pMMHodge0vzfk4yJgreSdpCAn9SpZnf5wkoXzjlceCqg1KTCPANRd2J8lHfWwv1XbvqTm0rLHPn9sFkOo/akyBoSpvt4yXRLgokWfnV2nCW5IB45GdTwFT6S6hnjzNaSdR1IqJtSq5LaX7EHS5ZLPboyDH+eXTUbmY5u0pTlhqxBRKQ==
  template:
    metadata:
      name: cam1-rtsp
      namespace: edge-newpark
