---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: uptime-push-url
  namespace: edge-newpark
spec:
  encryptedData:
    UPTIME_PUSH_URL: AgAzFxAaRTUYE9lzyk2JU8E8CUSvGSfj5eb2HEt87+vPQ58dn85zouibqT0g2Tgd2tCn8shR2eZZc0wjnOjc+wJrcz5tPp0ukTb1FwTE8KueW96vryy9kbu5sTUwhxsX36sierJnlwxnEqtG9+PpEYUy8lwXaQy/PDGZbDH/M9GhXKacmJ+FPcT6udjlD+i8QxAwc95DR0o7NgZWT3sg6BsfiaVjO3mSg7lUa0xE1yuwCeeywnQAPZ8wD/mKavfKm22pa0GCLlqaBaJ/dD2SCvzkCdIjsLN21NmHQH6K37s9nEdY0MVXhpmQBlqqwBjUgx4iERUpur55LHFP09nHkwkcSvaX/vD6ym63ETU/R583plI+kFzo4nn8lggCmnAuP97agjlE6LNa9Jb6ggYRSJurdgimMlqtanLavFgM06Boxyunu1Ov8ZC1w7wZI+vB8oKZNAsasE2iYp75m8QUCgx2RyDTFizGukEMlxss4VoVwlyLN5s5Kg1wrRvVtKROfX8n8xDebIHfR8zxZYe0zaWT1ckJt01Tr09h/dWRfjb1TxogXrhTQ78X6VjTaYwcsZv8H73wM1o+tEX5NB6Q8bS+qFM0exJgON5ED3lPRskljSCE2YZLzszokd50pOmhSEj2ApVxLgeCU96Esu1lOE5o+mmX7yGhm2gtsPE1gRbiDniWhGwbWGIpO5i7eOa1PX1Aw+jJ200Db0soHRVtZ8wfeu6T4zPIzaYXq15c9mhYfo/e3QX1M95fd32om8jG4QE0u/bnJtSkrYGrRozRTYOfHop91/UoDWPWiqnHuppu
  template:
    metadata:
      name: uptime-push-url
      namespace: edge-newpark
