---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: uptime-push-url
  namespace: default
spec:
  encryptedData:
    UPTIME_PUSH_URL: AgCgz58/vFQEqqnFqBpQ73u016QQvkK/nLTU8oujq2p7rpi6K8Cy7+8vjYxSQtNWMr3aLy1k1ZUkiR+jP/HZS9ps4VVy6X2JI0/Zjh7DxChIFl8tKT7ZwP6+TkRFvpo8pqed37t4iHavnqeriRqcz8p+Ri3V4njNAJZaGktM1sxLKO/nmdNsRqd4ZocdGqfhUbcxw3Fb7IwaVp1TlxQTS5YliuqgUTY/UfFfPSs2A96Ve91P66lnVz19ZuFkBOXxmQ4woKsA33gTQuP5EqXTpxOGZW45lroiqZgMJSN0e0cTMH8+GLa33oTpbz0Ld8ee6MEx4PAv6vX2D2Eg4yxltTaDRb7ctU3ztEogdVzwVNLIe9glCEWYXcseWKX3LJLFvr5Yw8YcuSYZdLLQahE4OWFyYDCETuwt9u0Ns4hiq1TmGgfQG6XjU3HH+dQRr0d0zj0z0bxoH3rp6sLFynbCkP5kaNQVGOBa5sf4j2FByVWd07VEBhoq+/BgzLFKdKvfBm2NEjgfBn3ESp3RTysOc/qzMTJ6GLfsxksuWWVPMnxqs+RpFaMEyPN8ngvKdCUc3BTCixBgsBdfgYzbl9jptgYusIMH7kZ6yIDfnozbFr2pDik/DSFJXOuQGT231XGCO1bwIwz0Oh+0r0OFtHTk4YQ5XE4DxvjFp5ZyLVv4MspnsGtkArNMXb0hneN54nv8TxJzwsDa/qJrr2lNwwHmYMY5l5+kq5ee5zJsQXf69oXtFFbDA3OawoULV2HTkOZKtJ1uSpU9hQctaK+VSh+2IOZ6PQHm/vPkSLDMtqQNtKUU
  template:
    metadata:
      name: uptime-push-url
      namespace: default
